#  University of Management & Technology
## Department of Artificial Intelligence | School of Systems & Technology
### Course: Programming Fundamentals for AI — CS3151L

---

#  Pandas Library — Interactive Lab Notebook

> **Instructions for Students:**  
> - Run each **Example** cell first to understand the concept.  
> - Then complete the **Task 1** and **Task 2** cells that follow each topic.  
> - Write your code where you see `# ✏️ YOUR CODE HERE`  
> - Do **NOT** modify the Example cells.

---
## ⚙️ Setup — Run This Cell First!

In [2]:
import pandas as pd
import numpy as np

---
#  Topic 1 — Creating a DataFrame from a Dictionary

**Concept:**  
A **DataFrame** is like a table (rows + columns). The simplest way to create one is from a Python **dictionary** where:
- **Keys** → Column names  
- **Values (lists)** → Column data

```python
pd.DataFrame( dictionary )
```

In [3]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Creating DataFrame from Dictionary
# ───────────────────────────────────────────
data = {
    'Name'    : ['Ali', 'Sara', 'Ahmed', 'Zara', 'Bilal'],
    'Age'     : [20, 22, 21, 23, 20],
    'CGPA'    : [3.5, 3.8, 3.2, 3.9, 3.1],
    'City'    : ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Multan'],

}

df=pd.DataFrame(data)

In [ ]:
df

    Name  Age  CGPA       City
0    Ali   20   3.5     Lahore
1   Sara   22   3.8    Karachi
2  Ahmed   21   3.2  Islamabad
3   Zara   23   3.9     Lahore
4  Bilal   20   3.1     Multan

In [ ]:
print(df)
print(df.shape)

    Name  Age  CGPA       City
0    Ali   20   3.5     Lahore
1   Sara   22   3.8    Karachi
2  Ahmed   21   3.2  Islamabad
3   Zara   23   3.9     Lahore
4  Bilal   20   3.1     Multan
(5, 4)

In [ ]:

df[['Age','Name']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     5 non-null      int64
 1   Name    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [ ]:
df.head(1)

  Name  Age  CGPA    City
0  Ali   20   3.5  Lahore

In [ ]:
df.tail(1)

### 📝 Task 1.1
Create a DataFrame called `df_books` from a dictionary with the following **5 books**:

| Title | Author | Year | Price | InStock |
|---|---|---|---|---|
| Python Crash Course | Eric Matthes | 2019 | 1500 | True |
| Deep Learning | Ian Goodfellow | 2016 | 4200 | False |
| Clean Code | Robert Martin | 2008 | 2800 | True |
| AI: A Modern Approach | Russell & Norvig | 2020 | 5500 | True |
| Hands-On ML | Aurelien Geron | 2022 | 3900 | False |

Then print the shape and display the DataFrame.

In [ ]:
# 📝 TASK 1.1 — Create df_books from a dictionary
# ✏️ YOUR CODE HERE

### 📝 Task 1.2
Create a DataFrame called `df_products` using a **list of dictionaries** (each dict = one product row).

Include at least **4 products** with columns: `ProductName`, `Category`, `Price`, `Stock`  
*(You can use any products you like — phones, laptops, etc.)*

Then print how many rows and columns are in the DataFrame.

In [ ]:
# 📝 TASK 1.2 — Create df_products from a list of dictionaries
# ✏️ YOUR CODE HERE

---
# 📌 Topic 2 — Exploring the DataFrame

**Key functions to explore data quickly:**

| Function | What it returns |
|---|---|
| `df.head(n)` | First n rows |
| `df.tail(n)` | Last n rows |
| `df.shape` | (rows, columns) |
| `df.info()` | Column types + null counts |
| `df.describe()` | Statistical summary |
| `df.dtypes` | Data type of each column |
| `df.columns` | List of column names |

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Exploring the DataFrame
# ───────────────────────────────────────────

print('── head(3) ──────────────────────────')
print(df.head(3))

print('\n── tail(2) ──────────────────────────')
print(df.tail(2))

print('\n── shape ────────────────────────────')
print('Rows:', df.shape[0], '| Columns:', df.shape[1])

print('\n── columns ──────────────────────────')
print(df.columns)

print('\n── dtypes ───────────────────────────')
print(df.dtypes)

print('\n── info() ───────────────────────────')
df.info()

print('\n── describe() ───────────────────────')
df.describe()

── head(3) ──────────────────────────
    Name  Age  CGPA       City
0    Ali   20   3.5     Lahore
1   Sara   22   3.8    Karachi
2  Ahmed   21   3.2  Islamabad

── tail(2) ──────────────────────────
    Name  Age  CGPA    City
3   Zara   23   3.9  Lahore
4  Bilal   20   3.1  Multan

── shape ────────────────────────────
Rows: 5 | Columns: 4

── columns ──────────────────────────
Index(['Name', 'Age', 'CGPA', 'City'], dtype='object')

── dtypes ───────────────────────────
Name     object
Age       int64
CGPA    float64
City     object
dtype: object

── info() ───────────────────────────
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   CGPA    5 non-null      float64
 3   City    5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

── describe() ───────────────────────

            Age      CGPA
count   5.00000  5.000000
mean   21.20000  3.500000
std     1.30384  0.353553
min    20.00000  3.100000
25%    20.00000  3.200000
50%    21.00000  3.500000
75%    22.00000  3.800000
max    23.00000  3.900000

### 📝 Task 2.1
Using your `df_books` DataFrame from Task 1.1:
1. Display the **first 2 rows** using `head()`
2. Display the **last 1 row** using `tail()`
3. Print the **column names** as a list
4. Print the **data types** of each column

In [ ]:
# 📝 TASK 2.1 — Explore df_books
# ✏️ YOUR CODE HERE

### 📝 Task 2.2
Using your `df_books` DataFrame:
1. Call `df_books.info()` and write a **comment** explaining what each line of output means
2. Call `df_books.describe()` and answer in comments:
   - What is the average Price?
   - What is the minimum Year?
   - What is the maximum Price?

In [ ]:
# 📝 TASK 2.2 — info() and describe() on df_books
# ✏️ YOUR CODE HERE


# Average Price    :
# Minimum Year     :
# Maximum Price    :

---
# 📌 Topic 3 — Selecting Columns

**Selecting a single column** → returns a **Series** (1D)
```python
df['ColumnName']
```

**Selecting multiple columns** → returns a **DataFrame** (2D)
```python
df[['Col1', 'Col2', 'Col3']]
```
> ⚠️ Notice the **double brackets** `[[ ]]` for multiple columns!

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Selecting Columns
# ───────────────────────────────────────────

# Single column → Series
print('── Single Column (Series) ───────────')
names = df['Name']
print(names)
print('Type:', type(names))

# Two columns → DataFrame
print('\n── Two Columns (DataFrame) ──────────')
name_cgpa = df[['Name', 'CGPA']]
print(name_cgpa)
print('Type:', type(name_cgpa))

# Three columns
print('\n── Three Columns ────────────────────')
print(df[['Name', 'Age', 'City']])

── Single Column (Series) ───────────
0      Ali
1     Sara
2    Ahmed
3     Zara
4    Bilal
Name: Name, dtype: object
Type: <class 'pandas.core.series.Series'>

── Two Columns (DataFrame) ──────────
    Name  CGPA
0    Ali   3.5
1   Sara   3.8
2  Ahmed   3.2
3   Zara   3.9
4  Bilal   3.1
Type: <class 'pandas.core.frame.DataFrame'>

── Three Columns ────────────────────
    Name  Age       City
0    Ali   20     Lahore
1   Sara   22    Karachi
2  Ahmed   21  Islamabad
3   Zara   23     Lahore
4  Bilal   20     Multan

### 📝 Task 3.1
Using `df_books`:
1. Select and print only the **`Title`** column (single column)
2. Check and print its **type** — is it a Series or DataFrame?
3. Select and print only the **`Author`** column

In [ ]:
# 📝 TASK 3.1 — Select single columns from df_books
# ✏️ YOUR CODE HERE

### 📝 Task 3.2
Using `df_books`:
1. Select and display **`Title` and `Price`** together
2. Select and display **`Title`, `Author`, and `Year`** together
3. Select and display **all columns except `InStock`** (hint: list the 4 columns you want)

In [ ]:
# 📝 TASK 3.2 — Select multiple columns from df_books
# ✏️ YOUR CODE HERE

---
# 📌 Topic 4 — Slicing Rows with iloc and loc

## `iloc` — Integer Location (Position-based)
Use when you know the **row/column number** (0, 1, 2...)
```python
df.iloc[row_position]
df.iloc[start:end]        # end is EXCLUSIVE
df.iloc[row, col]
```

## `loc` — Label Location (Name-based)
Use when you know the **row/column name or label**
```python
df.loc[row_label]
df.loc[start:end]         # end is INCLUSIVE
df.loc[row, 'ColName']
```

In [5]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — iloc (position-based)
# ───────────────────────────────────────────

print('── First row (iloc[0]) ──────────────')
df.iloc[0]

── First row (iloc[0]) ──────────────

Name       Ali
Age         20
CGPA       3.5
City    Lahore
Name: 0, dtype: object

In [ ]:
print('── Row with label 0 (loc[0]) ────────')
df.loc[0]

── Row with label 0 (loc[0]) ────────

Name       Ali
Age         20
CGPA       3.5
City    Lahore
Name: 0, dtype: object

In [6]:
print('\n── Rows 0 to 2, all columns ─────────')
df.loc[0:2]

── Rows 0 to 2, all columns ─────────

    Name  Age  CGPA       City
0    Ali   20   3.5     Lahore
1   Sara   22   3.8    Karachi
2  Ahmed   21   3.2  Islamabad

In [7]:
print('\n── Rows 0-2, columns Name to CGPA ───')
df.loc[0:2, 'Name':'CGPA']

── Rows 0-2, columns Name to CGPA ───

    Name  Age  CGPA
0    Ali   20   3.5
1   Sara   22   3.8
2  Ahmed   21   3.2

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — loc (label-based)
# ───────────────────────────────────────────



         # INCLUSIVE — includes row 2



print('\n── Specific rows and columns ────────')
print(df.loc[[1, 3], ['Name', 'City', 'CGPA']])

### 📝 Task 4.1
Using `df_books`, use **`iloc`** to:
1. Print the **2nd row** (index 1)
2. Print **rows 1 to 3** (using slice)
3. Print the **last 2 rows** (use negative indexing)
4. Print rows **0 and 2**, but only the **first 2 columns**

In [ ]:
# 📝 TASK 4.1 — iloc on df_books
# ✏️ YOUR CODE HERE

### 📝 Task 4.2
Using `df_books`, use **`loc`** to:
1. Print rows **0 to 2** (remember: loc is INCLUSIVE)
2. Print rows 1 and 3, showing only **`Title`** and **`Price`** columns
3. Print rows **0 to 3**, columns from **`Title`** to **`Year`**
4. In a comment, explain the difference you observed between `iloc` and `loc`

In [ ]:
# 📝 TASK 4.2 — loc on df_books
# ✏️ YOUR CODE HERE


# Difference between iloc and loc:
#

---
# 📌 Topic 5 — Filtering Rows (Boolean Indexing)

Filter rows by writing a **condition** inside `df[ ]`

```python
df[df['column'] > value]           # greater than
df[df['column'] == 'text']         # equals
df[condition1 & condition2]        # AND
df[condition1 | condition2]        # OR
df[df['col'].isin(['a', 'b'])]     # value in list
```
> ⚠️ Use `&` (not `and`) and `|` (not `or`) in Pandas conditions.  
> Wrap each condition in parentheses `( )`

In [8]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Filtering / Boolean Indexing
# ───────────────────────────────────────────

print('── Students with CGPA > 3.5 ─────────')
print(df[df['CGPA'] > 3.5])

print('\n── Students from Lahore ─────────────')
print(df[df['City'] == 'Lahore'])

print('\n── CGPA > 3.5 AND Age < 23 ──────────')
print(df[(df['CGPA'] > 3.5) & (df['Age'] < 23)])

print('\n── From Lahore OR CGPA > 3.8 ────────')
print(df[(df['City'] == 'Lahore') | (df['CGPA'] > 3.8)])

print('\n── isin(): from Lahore or Karachi ───')
print(df[df['City'].isin(['Lahore', 'Karachi'])])

── Students with CGPA > 3.5 ─────────
   Name  Age  CGPA     City
1  Sara   22   3.8  Karachi
3  Zara   23   3.9   Lahore

── Students from Lahore ─────────────
   Name  Age  CGPA    City
0   Ali   20   3.5  Lahore
3  Zara   23   3.9  Lahore

── CGPA > 3.5 AND Age < 23 ──────────
   Name  Age  CGPA     City
1  Sara   22   3.8  Karachi

── From Lahore OR CGPA > 3.8 ────────
   Name  Age  CGPA    City
0   Ali   20   3.5  Lahore
3  Zara   23   3.9  Lahore

── isin(): from Lahore or Karachi ───
   Name  Age  CGPA     City
0   Ali   20   3.5   Lahore
1  Sara   22   3.8  Karachi
3  Zara   23   3.9   Lahore

### 📝 Task 5.1
Using `df_books`, filter and display:
1. Books with **Price greater than 3000**
2. Books published **after year 2015**
3. Books that are **currently InStock** (InStock == True)

In [ ]:
# 📝 TASK 5.1 — Single-condition filtering
# ✏️ YOUR CODE HERE

### 📝 Task 5.2
Using `df_books`:
1. Filter books that are **InStock AND Price < 4000**
2. Filter books published **before 2018 OR Price > 5000**
3. Filter books by authors **'Eric Matthes' or 'Aurelien Geron'** using `isin()`

In [ ]:
# 📝 TASK 5.2 — Multi-condition filtering
# ✏️ YOUR CODE HERE

---
# 📌 Topic 6 — Sorting Data

```python
df.sort_values('col')                          # ascending (default)
df.sort_values('col', ascending=False)         # descending
df.sort_values(['col1','col2'])                 # sort by multiple columns
df.sort_values(['col1','col2'],
               ascending=[True, False])         # mixed order
```

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Sorting
# ───────────────────────────────────────────

print('── Sort by CGPA ascending ───────────')
print(df.sort_values('CGPA'))

print('\n── Sort by CGPA descending ──────────')
print(df.sort_values('CGPA', ascending=False))

print('\n── Sort by Age ASC, CGPA DESC ───────')
print(df.sort_values(['Age', 'CGPA'], ascending=[True, False]))

── Sort by CGPA ascending ───────────
    Name  Age  CGPA       City
4  Bilal   20   3.1     Multan
2  Ahmed   21   3.2  Islamabad
0    Ali   20   3.5     Lahore
1   Sara   22   3.8    Karachi
3   Zara   23   3.9     Lahore

── Sort by CGPA descending ──────────
    Name  Age  CGPA       City
3   Zara   23   3.9     Lahore
1   Sara   22   3.8    Karachi
0    Ali   20   3.5     Lahore
2  Ahmed   21   3.2  Islamabad
4  Bilal   20   3.1     Multan

── Sort by Age ASC, CGPA DESC ───────
    Name  Age  CGPA       City
0    Ali   20   3.5     Lahore
4  Bilal   20   3.1     Multan
2  Ahmed   21   3.2  Islamabad
1   Sara   22   3.8    Karachi
3   Zara   23   3.9     Lahore

### 📝 Task 6.1
Using `df_books`:
1. Sort by **Price** from cheapest to most expensive
2. Sort by **Year** from newest to oldest (descending)

In [ ]:
# 📝 TASK 6.1 — Sorting df_books
# ✏️ YOUR CODE HERE

### 📝 Task 6.2
Using `df_books`:
1. Sort by **InStock** first (True before False), then by **Price** ascending
2. Display only the **Title, Price, and InStock** columns of the sorted result

In [ ]:
# 📝 TASK 6.2 — Multi-column sort + column selection
# ✏️ YOUR CODE HERE

---
# 📌 Topic 7 — Adding and Removing Columns

```python
# Add a new column with constant value
df['NewCol'] = value

# Add a column calculated from existing columns
df['Total'] = df['Math'] + df['English']

# Remove a column (axis=1 means column)
df.drop('ColName', axis=1)             # returns new DataFrame
df.drop('ColName', axis=1, inplace=True)  # modifies in place
```

In [9]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Adding and Removing Columns
# ───────────────────────────────────────────

df_copy = df.copy()   # work on a copy so original df stays clean

# Add a column with a constant value
df_copy['University'] = 'UMT'

# Add a column calculated from another column
df_copy['CGPA_x10'] = df_copy['CGPA'] * 10

print('After adding columns:')
print(df_copy[['Name', 'CGPA', 'CGPA_x10', 'University']])

# Remove a column
df_copy.drop('University', axis=1, inplace=True)
print('\nAfter removing University column:')
print(df_copy.columns.tolist())

After adding columns:
    Name  CGPA  CGPA_x10 University
0    Ali   3.5      35.0        UMT
1   Sara   3.8      38.0        UMT
2  Ahmed   3.2      32.0        UMT
3   Zara   3.9      39.0        UMT
4  Bilal   3.1      31.0        UMT

After removing University column:
['Name', 'Age', 'CGPA', 'City', 'CGPA_x10']

### 📝 Task 7.1
Using a **copy** of `df_books` (use `df_books.copy()`):
1. Add a column **`DiscountedPrice`** = Price × 0.85 (15% discount)
2. Add a column **`Currency`** = `'PKR'` for all rows
3. Display the updated DataFrame

In [ ]:
# 📝 TASK 7.1 — Add columns to df_books copy
# ✏️ YOUR CODE HERE

### 📝 Task 7.2
Continuing on your copy from Task 7.1:
1. Remove the **`Currency`** column using `drop()`
2. Remove both **`DiscountedPrice`** and **`InStock`** at once (hint: pass a list)
3. Print the final column names to confirm removal

In [ ]:
# 📝 TASK 7.2 — Remove columns
# ✏️ YOUR CODE HERE

---
# 📌 Topic 8 — Statistical Functions

| Function | Returns |
|---|---|
| `.mean()` | Average |
| `.median()` | Middle value |
| `.std()` | Standard deviation |
| `.min()` / `.max()` | Smallest / Largest |
| `.sum()` | Total |
| `.count()` | Non-null count |
| `.value_counts()` | Frequency of each value |
| `.unique()` | Array of unique values |
| `.nunique()` | Number of unique values |

In [10]:
print('Mean  CGPA :', df['CGPA'].mean())
print('Median Age :', df['Age'].median())
print('Max   CGPA :', df['CGPA'].max())
print('Min   Age  :', df['Age'].min())
print('Std   CGPA :', round(df['CGPA'].std(), 3))
print('Count Name :', df['Name'].count())

print('\n── value_counts(): City ─────────────')
print(df['City'].value_counts())

print('\n── unique(): City ───────────────────')
print(df['City'].unique())

print('\n── nunique(): City ──────────────────')
print(df['City'].nunique())

Mean  CGPA : 3.5
Median Age : 21.0
Max   CGPA : 3.9
Min   Age  : 20
Std   CGPA : 0.354
Count Name : 5

── value_counts(): City ─────────────
City
Lahore       2
Karachi      1
Islamabad    1
Multan       1
Name: count, dtype: int64

── unique(): City ───────────────────
['Lahore' 'Karachi' 'Islamabad' 'Multan']

── nunique(): City ──────────────────
4

### 📝 Task 8.1
Using `df_books`:
1. Print the **average Price** of all books
2. Print the **maximum Price** and **minimum Price**
3. Print the **total sum** of all Prices
4. Print how many **unique years** appear in the Year column

In [ ]:
# 📝 TASK 8.1 — Statistics on df_books
# ✏️ YOUR CODE HERE

### 📝 Task 8.2
Using `df_books`:
1. Use `value_counts()` on **`InStock`** — how many books are in stock vs out of stock?
2. Find the **median Price**
3. Find the **standard deviation** of Price (round to 2 decimal places)
4. Print all **unique Author** names

In [ ]:
# 📝 TASK 8.2 — More statistics on df_books
# ✏️ YOUR CODE HERE

---
# 📌 Topic 9 — Handling Missing Values

Missing values appear as **NaN** (Not a Number). Pandas tools:

```python
df.isnull()          # True where value is NaN
df.isnull().sum()    # count of NaN per column
df.dropna()          # drop rows with any NaN
df.fillna(value)     # replace NaN with value
df['col'].fillna(df['col'].mean())   # fill with column mean
```

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — Handling Missing Values
# ───────────────────────────────────────────

# Create a DataFrame with NaN values
data_nan = {
    'Name' : ['Ali', 'Sara', None, 'Zara', 'Bilal'],
    'Score': [85, np.nan, 90, np.nan, 70],
    'Grade': ['A', 'A+', 'A', None, 'B+']
}
df_nan = pd.DataFrame(data_nan)

print('── Original DataFrame ───────────────')
print(df_nan)

print('\n── isnull() ─────────────────────────')
print(df_nan.isnull())

print('\n── Count of NaN per column ──────────')
print(df_nan.isnull().sum())

print('\n── After dropna() ───────────────────')
print(df_nan.dropna())

print('\n── Fill Score NaN with mean ─────────')
df_nan['Score'] = df_nan['Score'].fillna(df_nan['Score'].mean())
print(df_nan)

### 📝 Task 9.1
Run the cell below to create `df_missing`, then:
1. Check and print how many NaN values are in **each column**
2. Drop all rows that have **any NaN** and print the result

In [ ]:
# ── Run this cell to create df_missing ────
df_missing = pd.DataFrame({
    'StudentName': ['Ali', 'Sara', 'Ahmed', None,  'Zara'],
    'Math'       : [80,    np.nan, 75,      88,     np.nan],
    'English'    : [70,    85,     np.nan,  72,     90],
    'AI'         : [90,    92,     88,      np.nan, 85]
})
print(df_missing)

In [ ]:
# 📝 TASK 9.1 — Detect and drop missing values
# ✏️ YOUR CODE HERE

### 📝 Task 9.2
Using the original `df_missing` (re-run the setup cell above if needed):
1. Fill missing **Math** scores with the **mean** of the Math column
2. Fill missing **English** scores with the value **`0`**
3. Fill missing **AI** scores with the **median** of the AI column
4. Fill missing **StudentName** with the string `'Unknown'`
5. Print the final DataFrame — verify there are no NaN values left

In [ ]:
# 📝 TASK 9.2 — Fill missing values
df_missing2 = df_missing.copy()   # work on a copy
# ✏️ YOUR CODE HERE

---
# 📌 Topic 10 — apply() with Custom Functions

**`apply()`** runs a function on every element in a column.

```python
# Named function
def my_func(x):
    return x * 2
df['NewCol'] = df['Col'].apply(my_func)

# Lambda (one-line anonymous function)
df['NewCol'] = df['Col'].apply(lambda x: x * 2)
```

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — apply()
# ───────────────────────────────────────────

df_apply = df.copy()

# Named function
def grade_from_cgpa(cgpa):
    if cgpa >= 3.7:
        return 'A'
    elif cgpa >= 3.3:
        return 'B+'
    else:
        return 'B'

df_apply['LetterGrade'] = df_apply['CGPA'].apply(grade_from_cgpa)
print('── Grade using named function ───────')
print(df_apply[['Name', 'CGPA', 'LetterGrade']])

# Lambda function
df_apply['Senior'] = df_apply['Age'].apply(lambda x: 'Yes' if x >= 22 else 'No')
print('\n── Senior flag using lambda ─────────')
print(df_apply[['Name', 'Age', 'Senior']])

### 📝 Task 10.1
Using a copy of `df_books`:
1. Write a **named function** `price_category(price)` that returns:
   - `'Budget'` if price < 2000
   - `'Mid-range'` if price < 4000
   - `'Premium'` if price >= 4000
2. Apply it to create a new column **`Category`**
3. Display Title, Price, and Category

In [ ]:
# 📝 TASK 10.1 — apply() with named function
# ✏️ YOUR CODE HERE

### 📝 Task 10.2
Using a copy of `df_books`:
1. Use a **lambda** to create column **`PriceUSD`** = Price ÷ 280 (approximate PKR to USD)
2. Round PriceUSD to 2 decimal places (hint: `round(x, 2)` inside lambda)
3. Use a **lambda** to create column **`Availability`**: `'Available'` if InStock is True, else `'Sold Out'`
4. Display Title, Price, PriceUSD, and Availability

In [ ]:
# 📝 TASK 10.2 — apply() with lambda
# ✏️ YOUR CODE HERE

---
# 📌 Topic 11 — groupby() and Aggregation

**`groupby()`** splits data into groups and lets you compute statistics per group.

```python
df.groupby('GroupCol')['ValueCol'].mean()    # mean per group
df.groupby('GroupCol').agg(                  # multiple aggregations
    Avg = ('col', 'mean'),
    Total = ('col', 'sum'),
    Count = ('col', 'count')
)
```

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — groupby()
# ───────────────────────────────────────────

print('── Average CGPA per City ────────────')
print(df.groupby('City')['CGPA'].mean())

print('\n── Count of students per City ───────')
print(df.groupby('City')['Name'].count())

print('\n── Multiple aggregations ────────────')
summary = df.groupby('City').agg(
    Avg_CGPA = ('CGPA', 'mean'),
    Count    = ('Name', 'count'),
    Max_Age  = ('Age',  'max')
)
print(summary)

# print('\n── Count by Enrolled status ─────────')
# print(df.groupby('Enrolled')['Name'].count())

── Average CGPA per City ────────────
City
Islamabad    3.2
Karachi      3.8
Lahore       3.7
Multan       3.1
Name: CGPA, dtype: float64

── Count of students per City ───────
City
Islamabad    1
Karachi      1
Lahore       2
Multan       1
Name: Name, dtype: int64

── Multiple aggregations ────────────
           Avg_CGPA  Count  Max_Age
City
Islamabad       3.2      1       21
Karachi         3.8      1       22
Lahore          3.7      2       23
Multan          3.1      1       20

### 📝 Task 11.1
First run the cell below to create `df_class`, then:
1. Find the **average Marks** per **Subject**
2. Find the **count** of students per Subject

In [ ]:
# ── Run this cell first ───────────────────
df_class = pd.DataFrame({
    'Student': ['Ali','Sara','Ahmed','Zara','Bilal','Ali','Sara','Ahmed'],
    'Subject': ['Math','Math','Math','Math','AI','AI','AI','AI'],
    'Marks'  : [85, 92, 74, 88, 90, 78, 95, 70],
    'City'   : ['Lahore','Karachi','Islamabad','Lahore','Multan','Lahore','Karachi','Islamabad']
})
print(df_class)

  Student Subject  Marks       City
0     Ali    Math     85     Lahore
1    Sara    Math     92    Karachi
2   Ahmed    Math     74  Islamabad
3    Zara    Math     88     Lahore
4   Bilal      AI     90     Multan
5     Ali      AI     78     Lahore
6    Sara      AI     95    Karachi
7   Ahmed      AI     70  Islamabad

In [ ]:
# 📝 TASK 11.1 — groupby Subject
# ✏️ YOUR CODE HERE

### 📝 Task 11.2
Using `df_class`:
1. Group by **City** and find **average, min, and max** Marks using `agg()`
2. Group by **Subject** and find the **highest-scoring** student Marks

In [ ]:
# 📝 TASK 11.2 — groupby with agg()
# ✏️ YOUR CODE HERE

---
# 📌 Topic 12 — merge() and concat()

**`concat()`** — Stack DataFrames vertically (add rows) or horizontally (add columns)
```python
pd.concat([df1, df2], ignore_index=True)   # stack rows
```

**`merge()`** — Join DataFrames on a common column (like SQL JOIN)
```python
pd.merge(df1, df2, on='CommonColumn')      # inner join
pd.merge(df1, df2, on='Col', how='left')   # left join
```

In [ ]:
# ───────────────────────────────────────────
# ✅ EXAMPLE — concat() and merge()
# ───────────────────────────────────────────

batch1 = pd.DataFrame({'Name': ['Ali', 'Sara'],  'CGPA': [3.5, 3.8]})
batch2 = pd.DataFrame({'Name': ['Ahmed', 'Zara'], 'CGPA': [3.2, 3.9]})

print('── concat(): stack rows ─────────────')
all_students = pd.concat([batch1, batch2], ignore_index=True)
print(all_students)

# merge example
df_info    = pd.DataFrame({'Name': ['Ali','Sara','Ahmed'], 'CGPA': [3.5, 3.8, 3.2]})
df_contact = pd.DataFrame({'Name': ['Ali','Sara','Ahmed'], 'Email': ['ali@umt.edu','sara@umt.edu','ahmed@umt.edu']})

print('\n── merge(): join on Name ────────────')
merged = pd.merge(df_info, df_contact, on='Name')
print(merged)

### 📝 Task 12.1
1. Create `df_sem1` with columns `Name` and `Sem1_Marks` for 3 students
2. Create `df_sem2` with columns `Name` and `Sem2_Marks` for the same 3 students
3. **merge** them on `Name` to create `df_combined`
4. Add a column `Total` = Sem1_Marks + Sem2_Marks

In [ ]:
# 📝 TASK 12.1 — merge()
# ✏️ YOUR CODE HERE

### 📝 Task 12.2
1. Create `df_morning` with 3 students (Name, Section='Morning', Marks)
2. Create `df_evening` with 3 different students (Name, Section='Evening', Marks)
3. Use **`concat()`** to combine them with `ignore_index=True`
4. Print the combined DataFrame and its shape

In [ ]:
# 📝 TASK 12.2 — concat()
# ✏️ YOUR CODE HERE

---
# 🏆 Final Challenge — Bring It All Together!

This final challenge tests **all the concepts** from this lab.  
Read all steps carefully before writing any code.

**Scenario:** You are a data analyst for the AI Department at UMT.  
You have marks data for students across 3 subjects.

In [ ]:
# ── Run this cell to get the dataset ─────
np.random.seed(42)
df_final = pd.DataFrame({
    'RollNo'  : ['AI-001','AI-002','AI-003','AI-004','AI-005',
                 'AI-006','AI-007','AI-008','AI-009','AI-010'],
    'Name'    : ['Ali','Sara','Ahmed','Zara','Bilal',
                 'Hina','Usman','Fatima','Omar','Layla'],
    'Math'    : [85, 92, np.nan, 88, 67, 78, 91, 83, np.nan, 76],
    'English' : [78, 88, 80, 75, 70, np.nan, 84, 90, 72, 68],
    'AI'      : [90, 95, 72, 85, 60, 88, np.nan, 77, 82, 91],
    'City'    : ['Lahore','Karachi','Islamabad','Lahore','Multan',
                 'Karachi','Lahore','Islamabad','Multan','Karachi'],
    'Gender'  : ['M','F','M','F','M','F','M','F','M','F']
})
print('Dataset loaded! Shape:', df_final.shape)
df_final

In [ ]:
# 🏆 FINAL CHALLENGE — Complete all steps
# ──────────────────────────────────────────────────────────────────
# STEP 1: Fill missing Math scores with the MEAN of Math column
#         Fill missing English scores with the MEDIAN of English
#         Fill missing AI scores with the value 0
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 2: Add a column 'Total' = Math + English + AI
#         Add a column 'Percentage' = (Total / 300) * 100  (round to 1 decimal)
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 3: Add a column 'Grade' using apply() with a named function:
#   A+  if Percentage >= 90
#   A   if Percentage >= 80
#   B+  if Percentage >= 70
#   B   if Percentage >= 60
#   F   otherwise
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 4: Display the top 3 students by Percentage (sort descending)
#         Show only: Name, City, Percentage, Grade
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 5: Use groupby() to find average Percentage per City
#         Which city has the highest average percentage?
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 6: Filter only students with Grade 'A+' or 'A'
#         Print their names and percentages
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 7: Count how many students got each Grade using value_counts()
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE



# ──────────────────────────────────────────────────────────────────
# STEP 8: Save the final DataFrame to 'AI_Results.csv' (no index)
#         Then read it back and display the first 5 rows
# ──────────────────────────────────────────────────────────────────
# ✏️ YOUR CODE HERE

---
## ✅ Lab Submission Checklist

Before submitting, make sure you have completed all cells:

- [ ] Topic 1 — Tasks 1.1 and 1.2  
- [ ] Topic 2 — Tasks 2.1 and 2.2  
- [ ] Topic 3 — Tasks 3.1 and 3.2  
- [ ] Topic 4 — Tasks 4.1 and 4.2  
- [ ] Topic 5 — Tasks 5.1 and 5.2  
- [ ] Topic 6 — Tasks 6.1 and 6.2  
- [ ] Topic 7 — Tasks 7.1 and 7.2  
- [ ] Topic 8 — Tasks 8.1 and 8.2  
- [ ] Topic 9 — Tasks 9.1 and 9.2  
- [ ] Topic 10 — Tasks 10.1 and 10.2  
- [ ] Topic 11 — Tasks 11.1 and 11.2  
- [ ] Topic 12 — Tasks 12.1 and 12.2  
- [ ] Final Challenge — All 8 Steps  

**Submit:** `Pandas_Lab_UMT_YourRollNumber.ipynb`

---
*University of Management & Technology | Department of Artificial Intelligence | CS3151L*